# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: 6f3899f8
    url: /
    weight: 10
  - name: Papers
    identifier: 6e0cadca
    url: /#papers
    weight: 20
  - name: Talks
    identifier: f895e90d
    url: /#talks
    weight: 30
  - name: News
    identifier: 3546ec3f
    url: /#news
    weight: 40
  - name: Experience
    identifier: 1090f715
    url: experience/
    weight: 50
